name: elegant_alert_dialog
description: Dislpay a predefined alerts or custom alerts with support of multi-actions
version: 0.0.1
homepage: 'https://github.com/koukibadr/ElegantAlertDialog'
environment:
  sdk: '>=3.4.1 <4.0.0'
funding:
- 'https://www.buymeacoffee.com/koukibadr'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: null
